EXPERIMENT:
  NAME: ""
  TAG: "dist_gdkd,res32x4,shuv1"
  PROJECT: "cifar100_baselines_experimental"
DISTILLER:
  TYPE: "DIST_GDKD"
  TEACHER: "resnet32x4"
  STUDENT: "ShuffleV1"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.01
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
GDKD:
  W1: 1.0
  W2: 8.0
