EXPERIMENT:
  NAME: ""
  TAG: "teacher,res56"
  PROJECT: "cifar100_baselines"
DISTILLER:
  TYPE: "NONE"
  STUDENT: "resnet56"
DATASET:
  TYPE: "cifar100"
  ENHANCE_AUGMENT: true
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.05
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
