EXPERIMENT:
  NAME: ""
  TAG: "ti,lskd,res50,mobilenetv1"
  PROJECT: "transfer_baselines"
DATASET:
  TYPE: "tiny-imagenet"
  NUM_WORKERS: 4
  TEST:
    BATCH_SIZE: 128
DISTILLER:
  TYPE: "LSKD"
  TEACHER: "ResNet50"
  STUDENT: "MobileNetV1"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 100
  LR: 0.001
  LR_SCHEDULER: "step"
  LR_DECAY_STAGES: [30, 60]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.001
  MOMENTUM: 0.9
  TYPE: "SGD"
LSKD:
  TEMPERATURE: 2.0
  CE_WEIGHT: 0.5
  KD_WEIGHT: 9.0
LOG:
  TENSORBOARD_FREQ: 50
  SAVE_CHECKPOINT_FREQ: 5
