EXPERIMENT:
  NAME: ""
  TAG: "dtd,vanilla,res18"
  PROJECT: "transfer_baselines"
DATASET:
  TYPE: "dtd"
  ENHANCE_AUGMENT: true
  NUM_WORKERS: 4
  TEST:
    BATCH_SIZE: 128
DISTILLER:
  TYPE: "NONE"
  TEACHER: ""
  STUDENT: "ResNet18"
SOLVER:
  BATCH_SIZE: 32
  EPOCHS: 100
  LR: 0.001
  LR_SCHEDULER: "step"
  LR_DECAY_STAGES: [10, 30, 60]
  WEIGHT_DECAY: 0.0001
  MOMENTUM: 0.9
  TYPE: "SGD"
LOG:
  TENSORBOARD_FREQ: 50
  SAVE_CHECKPOINT_FREQ: 5
