EXPERIMENT:
  NAME: ""
  TAG: "reviewkd_gdkd,vgg13,vgg8"
  PROJECT: "cifar100_baselines_experimental"
DISTILLER:
  TYPE:  "REVIEWKD_GDKD"
  TEACHER: "vgg13"
  STUDENT: "vgg8"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.05
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
REVIEWKD:
  SHAPES: [1, 4, 4, 8, 16]
  OUT_SHAPES: [1, 4, 4, 8, 16]
  IN_CHANNELS: [128, 256, 512, 512, 512]
  OUT_CHANNELS: [128, 256, 512, 512, 512]
GDKD:
  W1: 1.0
  W2: 6.0