EXPERIMENT:
  NAME: ""
  TAG: "ti,dkd,res34,res18"
  PROJECT: "transfer_baselines"
DATASET:
  TYPE: "tiny-imagenet"
  NUM_WORKERS: 4
  TEST:
    BATCH_SIZE: 128
DISTILLER:
  TYPE: "DKD"
  TEACHER: "ResNet34"
  STUDENT: "ResNet18"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 100
  LR: 0.001
  LR_SCHEDULER: "step"
  LR_DECAY_STAGES: [30, 60]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.001
  MOMENTUM: 0.9
  TYPE: "SGD"
LOG:
  TENSORBOARD_FREQ: 50
  SAVE_CHECKPOINT_FREQ: 5
DKD:
  CE_WEIGHT: 1.0
  BETA: 0.5
  T: 1.0
  WARMUP: 1
