EXPERIMENT:
  NAME: ""
  TAG: "ti,kd,res34,res18"
  PROJECT: "transfer_baselines"
DATASET:
  TYPE: "tiny-imagenet"
  NUM_WORKERS: 32
  TEST:
    BATCH_SIZE: 128
DISTILLER:
  TYPE: "KD"
  TEACHER: "ResNet34"
  STUDENT: "ResNet18"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 100
  LR: 0.001
  LR_SCHEDULER: "step"
  LR_DECAY_STAGES: [30, 60]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.001
  MOMENTUM: 0.9
  TYPE: "SGD"
KD:
  TEMPERATURE: 1
  LOSS:
    CE_WEIGHT: 0.5
    KD_WEIGHT: 0.5
LOG:
  TENSORBOARD_FREQ: 50
  SAVE_CHECKPOINT_FREQ: 5
