EXPERIMENT:
  NAME: ""
  TAG: "ti,sgdkd,res34,res18"
  PROJECT: "transfer_baselines"
DATASET:
  TYPE: "tiny-imagenet"
  NUM_WORKERS: 16
  TEST:
    BATCH_SIZE: 512
DISTILLER:
  TYPE: "SGDKD"
  TEACHER: "ResNet34"
  STUDENT: "ResNet18"
SOLVER:
  BATCH_SIZE: 512
  EPOCHS: 100
  LR: 0.2
  LR_DECAY_STAGES: [30, 60, 90]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0001
  MOMENTUM: 0.9
  TYPE: "SGD"
LOG:
  TENSORBOARD_FREQ: 50
  SAVE_CHECKPOINT_FREQ: 10
SGDKD:
  CE_WEIGHT: 1.0
  W0: 0.5
  W1: 0.5
  ETA: 0.8
  T: 1.0
  WARMUP: 1
