EXPERIMENT:
  NAME: ""
  TAG: "vanilla,res50"
  PROJECT: "cub2011_baselines"
DATASET:
  TYPE: "cub2011"
  ENHANCE_AUGMENT: true
  NUM_WORKERS: 4
  TEST:
    BATCH_SIZE: 128
DISTILLER:
  TYPE: "NONE"
  TEACHER: ""
  STUDENT: "ResNet50"
SOLVER:
  BATCH_SIZE: 256
  EPOCHS: 300
  LR: 0.0025
  LR_SCHEDULER: "step"
  LR_DECAY_STAGES: [100, 200]
  WEIGHT_DECAY: 0.001
  MOMENTUM: 0.9
  TYPE: "SGD"
LOG:
  TENSORBOARD_FREQ: 50
  SAVE_CHECKPOINT_FREQ: 5
