EXPERIMENT:
  NAME: ""
  TAG: "cub2011,dist,res34,res18"
  PROJECT: "transfer_baselines"
DATASET:
  TYPE: "cub2011"
  NUM_WORKERS: 4
  TEST:
    BATCH_SIZE: 128
DISTILLER:
  TYPE: "DIST"
  TEACHER: "ResNet34"
  STUDENT: "ResNet18"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 100
  LR: 0.0025
  LR_SCHEDULER: "step"
  LR_DECAY_STAGES: [40, 80]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.001
  MOMENTUM: 0.9
  TYPE: "SGD"
DIST:
  T: 1.0
LOG:
  TENSORBOARD_FREQ: 50
  SAVE_CHECKPOINT_FREQ: 5
