EXPERIMENT:
  NAME: ""
  TAG: "reviewkd,res32x4,shuv2"
  PROJECT: "cifar100_baselines"
DISTILLER:
  TYPE: "REVIEWKD"
  TEACHER: "resnet32x4"
  STUDENT: "ShuffleV2"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.01
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
REVIEWKD:
  SHAPES: [1, 4, 8, 16]
  OUT_SHAPES: [1, 8, 16, 32]
  IN_CHANNELS: [116, 232, 464, 1024]
  OUT_CHANNELS: [64, 128, 256, 256]
