EXPERIMENT:
  NAME: ""
  TAG: "gdkd-autow1,res56,res20"
  PROJECT: "cifar100_baselines_experimental"
DISTILLER:
  TYPE: "GDKDAutoW1"
  TEACHER: "resnet56"
  STUDENT: "resnet20"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.05
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
GDKDAutoW1:
  W2: 2.0
