EXPERIMENT:
  NAME: ""
  TAG: "cub2011,ofd,res50,mobilenetv1"
  PROJECT: "transfer_baselines"
DATASET:
  TYPE: "cub2011"
  NUM_WORKERS: 4
  TEST:
    BATCH_SIZE: 128
DISTILLER:
  TYPE: "OFD"
  TEACHER: "ResNet50"
  STUDENT: "MobileNetV1"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 100
  LR: 0.0025
  LR_SCHEDULER: "step"
  LR_DECAY_STAGES: [40, 80]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.001
  MOMENTUM: 0.9
  TYPE: "SGD"
OFD:
  LOSS:
    FEAT_WEIGHT: 0.0001
LOG:
  TENSORBOARD_FREQ: 50
  SAVE_CHECKPOINT_FREQ: 5
