EXPERIMENT:
  NAME: ""
  TAG: "vanilla,mobilenetv1"
  PROJECT: "imagenet_baselines"
DATASET:
  TYPE: "tiny-imagenet"
  NUM_WORKERS: 8
  TEST:
    BATCH_SIZE: 128
DISTILLER:
  TYPE: "NONE"
  TEACHER: ""
  STUDENT: "ResNet34"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 40
  LR: 0.01
  LR_SCHEDULER: "cosine"
  LR_MIN: 0.00001
  WEIGHT_DECAY: 0.0001
  MOMENTUM: 0.9
  TYPE: "SGD"
LOG:
  TENSORBOARD_FREQ: 50
  SAVE_CHECKPOINT_FREQ: 5
