EXPERIMENT:
  NAME: ""
  TAG: "vanilla,res50"
  PROJECT: "imagenet_baselines"
DATASET:
  TYPE: "tiny-imagenet"
  NUM_WORKERS: 4
  TEST:
    BATCH_SIZE: 128
DISTILLER:
  TYPE: "NONE"
  TEACHER: ""
  STUDENT: "ResNet50"
SOLVER:
  BATCH_SIZE: 16
  EPOCHS: 50
  LR: 0.001
  LR_SCHEDULER: "cosine"
  LR_MIN: 0.000001
  WEIGHT_DECAY: 0.0001
  MOMENTUM: 0.9
  TYPE: "SGD"
LOG:
  TENSORBOARD_FREQ: 50
  SAVE_CHECKPOINT_FREQ: 5
